#!/bin/bash

set -e

echo
echo "===> Build started at $(date)"
echo
START=$SECONDS

# Unconditionally print elapsed build time at exit
function finish {
  echo "===> Elapsed time: $(($SECONDS - $START)) seconds"
}
trap finish EXIT

echo "---> Preparing source... ($SOURCE)"
mkdir -p $SOURCE

cp -Rf /tmp/src/. $SOURCE

cd $SOURCE

echo "---> Downloading dependencies..."
go get -v ./...

echo "---> Building application source as main in $SOURCE..."
go build -v -o main

echo
echo "===> Build completed at $(date)"

# Fix source directory permissions
fix-permissions ./
